import { RouteStop, Lead, Appointment, RegistrationEvent } from './types';

export const MOCK_ROUTES: RouteStop[] = [
  {
    id: '1',
    stopNumber: '01',
    patientName: 'Sarah Johnson',
    address: '422 Beacon St, Suite 402',
    timeSlot: '09:00 AM - 10:30 AM',
    careType: 'Post-Op Checkup',
    priority: 'HIGH',
  },
  {
    id: '2',
    stopNumber: '02',
    patientName: 'Michael Chen',
    address: '158 Commonwealth Ave',
    timeSlot: '11:00 AM - 12:00 PM',
    careType: 'Medication Mgmt',
    priority: 'STANDARD',
  },
  {
    id: '3',
    stopNumber: '03',
    patientName: 'Elena Rodriguez',
    address: '29 Boylston St',
    timeSlot: '01:30 PM - 02:30 PM',
    careType: 'Physical Therapy',
    priority: 'STANDARD',
  },
  {
    id: '4',
    stopNumber: '04',
    patientName: 'David Miller',
    address: '72 Hanover St',
    timeSlot: '03:00 PM - 04:00 PM',
    careType: 'Vitals Screening',
    priority: 'LOWER',
  },
];

export const MOCK_LEADS: Lead[] = [
  {
    id: 'l1',
    initials: 'JS',
    name: 'James Sullivan',
    leadId: '#99021-LA',
    phone: '+1 (555) 012-3456',
    location: 'West Valley, CA',
    lastActivity: 'Just now (System Scan)',
    status: 'New',
  },
  {
    id: 'l2',
    initials: 'EM',
    name: 'Elena Martinez',
    leadId: '#99025-NY',
    phone: '+1 (555) 888-0912',
    location: 'East Metropolitan',
    lastActivity: '2h ago (Missed Call)',
    status: 'Contacted',
  },
  {
    id: 'l3',
    initials: 'RB',
    name: 'Robert Brown',
    leadId: '#99031-FL',
    phone: '+1 (555) 767-1122',
    location: 'South Coastal',
    lastActivity: '5h ago (Appointment Set)',
    status: 'Interested',
  },
  {
    id: 'l4',
    initials: 'SP',
    name: 'Sarah Parker',
    leadId: '#99042-TX',
    phone: '+1 (555) 234-5678',
    location: 'Austin, TX',
    lastActivity: '1d ago (Email Inquiry)',
    status: 'Interested',
  },
  {
    id: 'l5',
    initials: 'DK',
    name: 'David Kim',
    leadId: '#99055-CA',
    phone: '+1 (555) 901-2345',
    location: 'Los Angeles, CA',
    lastActivity: 'Closed: 2d ago',
    status: 'Not Interested',
  },
];

export const UPCOMING_APPOINTMENTS: Appointment[] = [
  {
    id: 'a1',
    patientName: 'Sarah Johnson',
    type: 'Post-Op Review',
    time: '09:30 AM',
    date: 'Oct 24',
    status: 'In 2h',
  },
  {
    id: 'a2',
    patientName: 'Robert Miller',
    type: 'New Patient Consult',
    time: '11:15 AM',
    date: 'Oct 24',
    status: 'Scheduled',
  },
];

export const REGISTRATION_EVENTS: RegistrationEvent[] = [
  {
    id: 'e1',
    patientName: 'Adrian Hoffman',
    initials: 'AH',
    mrn: 'MRN-902-114',
    time: 'Oct 31, 14:22 PM',
    facility: 'East Wing Cardiology',
    status: 'Validated',
  },
  {
    id: 'e2',
    patientName: 'Elena Brooks',
    initials: 'EB',
    mrn: 'MRN-781-445',
    time: 'Oct 31, 13:05 PM',
    facility: 'Main Trauma Unit',
    status: 'Pending',
  },
  {
    id: 'e3',
    patientName: 'Samuel Miller',
    initials: 'SM',
    mrn: 'MRN-223-908',
    time: 'Oct 31, 11:58 AM',
    facility: 'North Lab Analytics',
    status: 'Validated',
  },
  {
    id: 'e4',
    patientName: 'Julianna Wright',
    initials: 'JW',
    mrn: 'MRN-112-550',
    time: 'Oct 31, 09:12 AM',
    facility: 'Paediatric Ward',
    status: 'Critical Review',
  },
];
